"""Initial migration

Revision ID: 0001_initial
Revises: 
Create Date: 2026-02-18 13:31:40.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('cpf', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token', name='uq_users_token'),
        sa.Index('ix_users_id', 'id'),
        sa.Index('ix_users_token', 'token')
    )
    op.create_table(
        'events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('radius', sa.Float(), nullable=False),
        sa.Column('start_time', sa.Float(), nullable=False),
        sa.Column('end_time', sa.Float(), nullable=False),
        sa.Column('salt', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_events_id', 'id')
    )
    op.create_table(
        'themes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.String(), nullable=False),
        sa.Column('options', sa.Text(), nullable=False),
        sa.Column('open_time', sa.Float(), nullable=False),
        sa.Column('close_time', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_themes_id', 'id')
    )
    op.create_table(
        'checkins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.Float(), nullable=False),
        sa.Column('photo_hash', sa.String(), nullable=True),
        sa.Column('leaf_hash', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id', 'user_id', name='uq_checkin_user_per_event'),
        sa.Index('ix_checkins_id', 'id')
    )
    op.create_table(
        'vote_tokens',
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('theme_id', sa.Integer(), nullable=False),
        sa.Column('user_hash', sa.String(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.ForeignKeyConstraint(['theme_id'], ['themes.id']),
        sa.PrimaryKeyConstraint('token'),
        sa.UniqueConstraint('theme_id', 'user_hash', name='uq_vote_token_user_per_theme'),
        sa.Index('ix_vote_tokens_token', 'token')
    )
    op.create_table(
        'votes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('theme_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('option', sa.String(), nullable=False),
        sa.Column('leaf_hash', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['theme_id'], ['themes.id']),
        sa.ForeignKeyConstraint(['token'], ['vote_tokens.token']),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_votes_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('vote_tokens')
    op.drop_table('checkins')
    op.drop_table('themes')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
